version: '3'
services:
  postgresql_dev:
    container_name: postgresql_dev
    restart: always
    build:
      context: ./
      dockerfile: ./docker/postgresql/Dockerfile.dev
    ports:
      - "5432:5432"
  postgresql_test:
    container_name: postgresql_test
    restart: always
    build:
      context: ./
      dockerfile: ./docker/postgresql/Dockerfile.test
    ports:
      - "6543:5432"
